// Generated by CoffeeScript 1.9.2
window.requestFileSystem = window.requestFileSystem || window.webkitRequestFileSystem;

document.addEventListener('DOMContentLoaded', function(eventLoaded) {
  var elem;
  elem = document.querySelector('#dev-src-dropzone');
  elem.addEventListener('dragover', function(event) {
    console.log('dragover', event);
    event.stopPropagation();
    event.preventDefault();
    return event.dataTransfer.dropEffect = 'copy';
  });
  return elem.addEventListener('drop', function(event) {
    console.log('drop', event);
    event.stopPropagation();
    return event.preventDefault();
  });
});

//# sourceMappingURL=dev.js.map
