// Generated by CoffeeScript 1.9.2
var connections, log, version,
  slice = [].slice;

version = '0.0.1';

log = function() {
  var args;
  args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
  return console.log.apply(console, ['shw', version].concat(slice.call(args)));
};

connections = 0;

log('connections', connections);

self.addEventListener('connect', function(event) {
  var port;
  log('connect', event);
  port = event.ports[0];
  connections++;
  port.addEventListener('message', function(event) {
    log('message', event);
    return port.postMessage('hello ' + event.data + ' ' + connections);
  });
  return port.start();
}, false);

//# sourceMappingURL=jsworker.js.map
