// Generated by CoffeeScript 1.9.2
window.sworker = function(msg) {
  return new Promise(function(resolve, reject) {
    var channel;
    channel = new MessageChannel();
    console.log('promise');
    channel.port1.onmessage = function(event) {
      console.log('onmessage', event);
      if (event.data.error) {
        return reject(event.data.error);
      } else {
        return resolve(event.data);
      }
    };
    return navigator.serviceWorker.controller.postMessage(msg, [channel.port2]);
  });
};

window.offerClicked = function(event) {
  var conf, content, url;
  console.log('offerClicked', event);
  url = document.querySelector('#url').value.trim();
  content = document.querySelector('#data').value.trim();
  console.log('url', url, data);
  window.sworker({
    command: 'keys'
  }).then(function(data) {
    return console.log('keys', data);
  });
  if (url.length !== 0) {
    console.log(url, data);
    window.sworker({
      command: 'add',
      url: url,
      content: content.length === 0 ? null : content
    }).then(function(data) {
      return console.log('add', url, content, data);
    });
  }
  conf = RTC({
    room: 'b2ornot2b:test',
    signaller: 'http://128.199.127.220:8997',
    constraints: null,
    channels: {
      chat: true
    },
    ice: [
      {
        url: 'stun:stun1.l.google.com:19302'
      }, {
        url: 'stun:stun2.l.google.com:19302'
      }, {
        url: 'stun:stun3.l.google.com:19302'
      }, {
        url: 'stun:stun4.l.google.com:19302'
      }
    ]
  });
  return conf.on('channel:opened:chat', function(id, channel, attributes, connection) {
    console.log('channel:opened:chat', id, channel, attributes, connection);
    return channel.onmessage = function(event) {
      return console.log('msg: ', event.data);
    };
  });
};

//# sourceMappingURL=main.js.map
