// Generated by CoffeeScript 1.9.3
console.log('service worker');

self.addEventListener('install', function(event) {
  return console.log('service worker install', event);
});

self.addEventListener('activate', function(event) {
  return console.log('service worker activate', event);
});

self.addEventListener('fetch', function(event) {
  return console.log('service worker fetch', event);
});

//# sourceMappingURL=service-worker.js.map
