// Generated by CoffeeScript 1.9.2
var log, version,
  slice = [].slice;

version = '0.0.1';

log = function() {
  var args;
  args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
  return console.log.apply(console, ['sew', version].concat(slice.call(args)));
};

log('service worker', version);

self.addEventListener('install', function(event) {
  return log('install', event);
});

self.addEventListener('activate', function(event) {
  return log('activate', event);
});

self.addEventListener('fetch', function(event) {
  return log('fetch', event);
});

//# sourceMappingURL=service-worker.js.map
